### ISSUE TITLE
Installation struggles

### ISSUE THREAD

**Issue by stuartburrell** [bottler/iisignature#1]
Hi,

After running pip install iisignature on linux, I'm getting the following error:

>>> import iisignature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/stuart/anaconda2/lib/python2.7/site-packages/iisignature.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

I was wondering if you knew how to fix this?

Cheers,

Stuart

**Comment by bottler** [comment]
Looking at other instances of this error on the web, it looks like a mismatch in the way the compilation is happening. I don't know anaconda, but the following might help::

    pip uninstall iisignature # to get rid of the broken one
    conda install libgcc # to update conda's tools
    conda install iisignature # to install the anaconda way

**Comment by bottler** [comment]
I just downloaded and installed the latest anaconda (version 4.4) for python 2.7, ran `pip install iisignature`, and then tried to use it and got the same error as you. The following fixed it for me::

    pip uninstall iisignature
    conda install libgcc
    pip install --no-cache iisignature

I was wrong before about using conda to install,

**Comment by stuartburrell** [comment]
Thanks very much for the help! That's fixed the issue for me too.
