### ISSUE TITLE
Is it straight forward to get the log signatures form this matlab code.

### ISSUE THREAD

**Issue by creator2020A** [bottler/iisignature#11]
As per my understanding the matlab code above calculates signature or the iterated integrals can we get the log signatures easily from this code?

**Comment by bottler** [comment]
It's just signatures. It's would be a piece of work to calculate log signatures as well - one easyish way would be to translate the mathematica code.

If you only care about log signatures up to level 2 or 3, then it would be quite easy to implement.

**Comment by creator2020A** [comment]
yes, actually I need only upto level 3.
