### ISSUE TITLE
Could not install iisignature in Windows 10 - Python3.9.

### ISSUE THREAD

**Issue by creator2020A** [bottler/iisignature#12]
I got the following messgae although I have Microsoft Visual C++

C:\Users\r.acharyya.CI\AppData\Local\Programs\Python\Python39\Scripts>pip install iisignature
Collecting iisignature
  Using cached iisignature-0.24.tar.gz (1.3 MB)
Requirement already satisfied: numpy>1.7 in c:\users\r.acharyya.ci\appdata\local\programs\python\python39\lib\site-packages (from iisignature) (1.19.4)
Building wheels for collected packages: iisignature
  Building wheel for iisignature (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\r.acharyya.ci\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"'; __file__='"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\r.acharyya.CI\AppData\Local\Temp\pip-wheel-4c889u7m'
       cwd: C:\Users\r.acharyya.CI\AppData\Local\Temp\pip-install-pyntgbhl\iisignature\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\iisignature_data
  copying iisignature_data\__init__.py -> build\lib.win-amd64-3.9\iisignature_data
  copying iisignature_data\bchLyndon20.dat -> build\lib.win-amd64-3.9\iisignature_data
  running build_ext
  building 'iisignature' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for iisignature
  Running setup.py clean for iisignature
Failed to build iisignature
Installing collected packages: iisignature
    Running setup.py install for iisignature ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\r.acharyya.ci\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"'; __file__='"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\r.acharyya.CI\AppData\Local\Temp\pip-record-dclsnq17\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\r.acharyya.ci\appdata\local\programs\python\python39\Include\iisignature'
         cwd: C:\Users\r.acharyya.CI\AppData\Local\Temp\pip-install-pyntgbhl\iisignature\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\iisignature_data
    copying iisignature_data\__init__.py -> build\lib.win-amd64-3.9\iisignature_data
    copying iisignature_data\bchLyndon20.dat -> build\lib.win-amd64-3.9\iisignature_data
    running build_ext
    building 'iisignature' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\r.acharyya.ci\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"'; __file__='"'"'C:\\Users\\r.acharyya.CI\\AppData\\Local\\Temp\\pip-install-pyntgbhl\\iisignature\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\r.acharyya.CI\AppData\Local\Temp\pip-record-dclsnq17\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\r.acharyya.ci\appdata\local\programs\python\python39\Include\iisignature' Check the logs for full command output.

C:\Users\r.acharyya.CI\AppData\Local\Programs\Python\Python39\Scripts>

**Comment by bottler** [comment]
Python 3.9 is very new. There isn't a prebuilt wheel on pypi yet for python 3.9. Hopefully soon.
Can you use Python 3.8?

**Comment by creator2020A** [comment]
Hi ,

Sure, I will try. Thank you for the clarification.

Best regards

Ranjan

**Comment by bottler** [comment]
I have now uploaded wheels to pypi for 3.9.

**Comment by creator2020A** [comment]
Hi Jeremy,  thank you.  I will try soon. Ranjan

**Comment by creator2020A** [comment]
Yes it worked. Thanks a lot.
