### ISSUE TITLE
Is there any limitation on size of the matrix for which signature can be calculated?

### ISSUE THREAD

**Issue by creator2020A** [bottler/iisignature#15]
I get this when I try to calculate signature:

    ab1R=iisignature.sig(dab01Real,2)
ValueError: negative dimensions are not allowed

the size of  dab01Real is (2, 304128)

**Comment by bottler** [comment]
This is a massive calculation. It asks for the signature of a 304128-dimensional path up to level 2. The answer will have 92494144512 entries. In single precision floats, it will require over 450 GB to store the result, and the working memory requirement will be several times that. If you are running 32 bit this is impossible. iisignature may not always be careful about making things like this work in 64bit (assuming the memory was available). 

If you mean a 2 dimensional path with 304128 points, you need to transpose the input first.

**Comment by creator2020A** [comment]
Thank you, yes, mine is 64 bit but do no thave 450 GB.
