### ISSUE TITLE
Segmentation fault using prepare with the aim to use the `logsigtosig` function

### ISSUE THREAD

**Issue by jambo6** [bottler/iisignature#16]
Would really like to use logsigtosig for a project, however, when running for example
```
iisignature.prepare(3, 3, '2')
```
Python automatically closes with 
```
segmentation fault  python
```
Am I using this correctly?

**Comment by bottler** [comment]
Sorry, this is a simple bug. If you want to use logsigtosig, you need to not only have `2` in the prepare string but also request the `S` method. Can you try `iisignature.prepare(3, 3, '2S')`?

**Comment by jambo6** [comment]
Works great now, thankyou!
