### ISSUE TITLE
Error in installing iisignature

### ISSUE THREAD

**Issue by rananimit** [bottler/iisignature#17]
Hello
I am trying to install iisignature via visual studio code terminal (in MacOS) using pip install iisignature but getting the following error. Can anyone suggest how to overcome this? Thank you very much in advance.

Building wheels for collected packages: iisignature
  Building wheel for iisignature (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
exit code: 1
  ╰─> [123 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/iisignature_data
      copying iisignature_data/__init__.py -> build/lib.macosx-10.9-universal2-3.10/iisignature_data
      copying iisignature_data/bchLyndon20.dat -> build/lib.macosx-10.9-universal2-3.10/iisignature_data
      running build_ext
      building 'iisignature' extension
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DVERSION=0.24 -I/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/pythonsigs.cpp -o build/temp.macosx-10.9-universal2-3.10/src/pythonsigs.o -std=c++11
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:32:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
      #error Unsupported architecture
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
      #error architecture not supported
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
      typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_dev_t;         /* dev_t */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
      typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
      typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
      typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
      typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
              ^
      note: '__uint128_t' declared here
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_wctype_t;
              ^
      note: '__uint128_t' declared here
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:152:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_ssize_t.h:30:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
      #error architecture not supported
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:152:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_ssize_t.h:31:9: error: unknown type name '__darwin_ssize_t'; did you mean '__darwin_blksize_t'?
      typedef __darwin_ssize_t        ssize_t;
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:25: note: '__darwin_blksize_t' declared here
      typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
                              ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for iisignature
  Running setup.py clean for iisignature
Failed to build iisignature
Installing collected packages: iisignature
  Running setup.py install for iisignature ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for iisignature did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/iisignature_data
      copying iisignature_data/__init__.py -> build/lib.macosx-10.9-universal2-3.10/iisignature_data
      copying iisignature_data/bchLyndon20.dat -> build/lib.macosx-10.9-universal2-3.10/iisignature_data
      running build_ext
      building 'iisignature' extension
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DVERSION=0.24 -I/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/pythonsigs.cpp -o build/temp.macosx-10.9-universal2-3.10/src/pythonsigs.o -std=c++11
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:32:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
      #error Unsupported architecture
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
      #error architecture not supported
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
      typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_dev_t;         /* dev_t */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
      typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
      typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
      typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
      typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
      typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
              ^
      note: '__int128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
              ^
      note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
              ^
      note: '__uint128_t' declared here
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_wctype_t;
              ^
      note: '__uint128_t' declared here
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:152:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_ssize_t.h:30:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
      #error architecture not supported
       ^
      In file included from src/pythonsigs.cpp:12:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:203:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:152:
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_ssize_t.h:31:9: error: unknown type name '__darwin_ssize_t'; did you mean '__darwin_blksize_t'?
      typedef __darwin_ssize_t        ssize_t;
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:25: note: '__darwin_blksize_t' declared here
      typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
                              ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> iisignature

note: This is an issue with the package mentioned above, not pip.

**Comment by bottler** [comment]
Can you try `MACOSX_DEPLOYMENT_TARGET=10.9 pip install iisignature`?

**Comment by rananimit** [comment]
Thank you for the suggestion but I have got the same error as follows

Building wheel for iisignature (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
.
.
.
fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for iisignature
  Running setup.py clean for iisignature
Failed to build iisignature
.
.
.
fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> iisignature

Could you please suggest something else?

**Comment by bottler** [comment]
Are you on an intel cpu or apple silicon?

**Comment by rananimit** [comment]
It is intel cpu.

**Comment by bottler** [comment]
I just tried building iisignature on a mac and had no problems. I'm afraid I have no idea how to help. Could it be to do with installing xcode developer tools, which I think I have up to date? And the clang version?

```
(iis) reizenstein-mbp:~$ clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(iis) reizenstein-mbp:~$ which clang
/usr/bin/clang
```

**Comment by rananimit** [comment]
I am not using Xcode to install it. I have tried to install iisignature package via VS code terminal. Will it make difference? Could you tell me the steps to follow to install it in Xcode developer tools?
I have the following clang version:
 ~ % clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by bottler** [comment]
I am not using xcode explicitly. I just think I am relying on it being installed for the compilation to work. 

You have an old clang version. I think clang and some of the system libraries it uses should be upgraded by installing the xcode command line tools from apple. Then try again.

**Comment by rananimit** [comment]
Thank you very much. Updation work.
