### ISSUE TITLE
Problem in Installing 'iisignature' package

### ISSUE THREAD

**Issue by rananimit** [bottler/iisignature#22]
Hi 
I am getting the following error while installing iisignature package using the following commands:

pip uninstall iisignature
conda install libgcc
pip install --no-cache iisignature

Error message: 
Failed to build iisignature
ERROR: Could not build wheels for iisignature, which is required to install pyproject.toml-based projects

I have python 3.10.4 at my end.

Could anyone please suggest a solution to this problem?

**Comment by bottler** [comment]
Can you share the actual build error? Perhaps try `pip install -v -v -v --no-cache iisignature` ?

**Comment by rananimit** [comment]
Thank you for your reply. I have managed to install it now.
