### ISSUE TITLE
Negative siglength

### ISSUE THREAD

**Issue by baondq** [bottler/iisignature#26]
I tried this function and got negative value of siglength:

`print(iisignature.siglength(9500,2)`

The result is `-170383`

iisignature version: 0.24
numpy version: 1.26.4
python version: 3.10.14
OS: Windows 11

Why is the result negative?

**Comment by bottler** [comment]
Thanks for the bug report. The calculation was overflowing internally and should now be fixed if you install from master.

iisignature.siglength(9,9) is also now working.
