### ISSUE TITLE
add setup_requires to setup.py

### ISSUE THREAD

**Issue by miktoki** [bottler/iisignature#4]
in `setup.py` you have the line 
> install_requires=['numpy>1.7'], #For now, this is redundant as we've died above here on an import statement

Could you add the requirement under `setup_requires` as well, so as to signify that it is a requirement also for the setup script? eg: 
> setup_requires=['numpy>1.7']

setup_requires (from https://setuptools.readthedocs.io/en/latest/setuptools.html)

    A string or list of strings specifying what other distributions need to be present in order
    for the setup script to run. setuptools will attempt to obtain these (even going so far as
    to download them using EasyInstall) before processing the rest of the setup script or
    commands. This argument is needed if you are using distutils extensions as part of
    your build process; for example, extensions that process setup() arguments and turn 
    them into EGG-INFO metadata files.

**Comment by bottler** [comment]
done.
